In [5]:
import pandas as pd

df = pd.read_csv('pokemon_data.csv')
print(df.head())

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False

In [6]:
#printing columns
print(df.columns)

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [11]:
# printing specific columns
print(df[['Name','Attack','Type 1' ]])

                      Name  Attack   Type 1
0                Bulbasaur      49    Grass
1                  Ivysaur      62    Grass
2                 Venusaur      82    Grass
3    VenusaurMega Venusaur     100    Grass
4               Charmander      52     Fire
..                     ...     ...      ...
795                Diancie     100     Rock
796    DiancieMega Diancie     160     Rock
797    HoopaHoopa Confined     110  Psychic
798     HoopaHoopa Unbound     160  Psychic
799              Volcanion     110     Fire

[800 rows x 3 columns]

In [14]:
#printing rows
print(df.iloc[0:4])

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False

In [15]:
# Read a specific location (R,C)
print(df.iloc[2,1])

Venusaur

In [18]:
for index, row in df.iterrows():
    print(index, row['Type 1'])

0 Grass
1 Grass
2 Grass
3 Grass
4 Fire
5 Fire
6 Fire
7 Fire
8 Fire
9 Water
10 Water
11 Water
12 Water
13 Bug
14 Bug
15 Bug
16 Bug
17 Bug
18 Bug
19 Bug
20 Normal
21 Normal
22 Normal
23 Normal
24 Normal
25 Normal
26 Normal
27 Normal
28 Poison
29 Poison
30 Electric
31 Electric
32 Ground
33 Ground
34 Poison
35 Poison
36 Poison
37 Poison
38 Poison
39 Poison
40 Fairy
41 Fairy
42 Fire
43 Fire
44 Normal
45 Normal
46 Poison
47 Poison
48 Grass
49 Grass
50 Grass
51 Bug
52 Bug
53 Bug
54 Bug
55 Ground
56 Ground
57 Normal
58 Normal
59 Water
60 Water
61 Fighting
62 Fighting
63 Fire
64 Fire
65 Water
66 Water
67 Water
68 Psychic
69 Psychic
70 Psychic
71 Psychic
72 Fighting
73 Fighting
74 Fighting
75 Grass
76 Grass
77 Grass
78 Water
79 Water
80 Rock
81 Rock
82 Rock
83 Fire
84 Fire
85 Water
86 Water
87 Water
88 Electric
89 Electric
90 Normal
91 Normal
92 Normal
93 Water
94 Water
95 Poison
96 Poison
97 Water
98 Water
99 Ghost
100 Ghost
101 Ghost
102 Ghost
103 Rock
104 Psychic
105 Psychic
106 Water
107 Water
108 Electric
109 Electric
110 Grass
111 Grass
112 Ground
113 Ground
114 Fighting
115 Fighting
116 Normal
117 Poison
118 Poison
119 Ground
120 Ground
121 Normal
122 Grass
123 Normal
124 Normal
125 Water
126 Water
127 Water
128 Water
129 Water
130 Water
131 Psychic
132 Bug
133 Ice
134 Electric
135 Fire
136 Bug
137 Bug
138 Normal
139 Water
140 Water
141 Water
142 Water
143 Normal
144 Normal
145 Water
146 Electric
147 Fire
148 Normal
149 Rock
150 Rock
151 Rock
152 Rock
153 Rock
154 Rock
155 Normal
156 Ice
157 Electric
158 Fire
159 Dragon
160 Dragon
161 Dragon
162 Psychic
163 Psychic
164 Psychic
165 Psychic
166 Grass
167 Grass
168 Grass
169 Fire
170 Fire
171 Fire
172 Water
173 Water
174 Water
175 Normal
176 Normal
177 Normal
178 Normal
179 Bug
180 Bug
181 Bug
182 Bug
183 Poison
184 Water
185 Water
186 Electric
187 Fairy
188 Normal
189 Fairy
190 Fairy
191 Psychic
192 Psychic
193 Electric
194 Electric
195 Electric
196 Electric
197 Grass
198 Water
199 Water
200 Rock
201 Water
202 Grass
203 Grass
204 Grass
205 Normal
206 Grass
207 Grass
208 Bug
209 Water
210 Water
211 Psychic
212 Dark
213 Dark
214 Water
215 Ghost
216 Psychic
217 Psychic
218 Normal
219 Bug
220 Bug
221 Normal
222 Ground
223 Steel
224 Steel
225 Fairy
226 Fairy
227 Water
228 Bug
229 Bug
230 Bug
231 Bug
232 Bug
233 Dark
234 Normal
235 Normal
236 Fire
237 Fire
238 Ice
239 Ice
240 Water
241 Water
242 Water
243 Ice
244 Water
245 Steel
246 Dark
247 Dark
248 Dark
249 Water
250 Ground
251 Ground
252 Normal
253 Normal
254 Normal
255 Fighting
256 Fighting
257 Ice
258 Electric
259 Fire
260 Normal
261 Normal
262 Electric
263 Fire
264 Water
265 Rock
266 Rock
267 Rock
268 Rock
269 Psychic
270 Fire
271 Psychic
272 Grass
273 Grass
274 Grass
275 Grass
276 Fire
277 Fire
278 Fire
279 Fire
280 Water
281 Water
282 Water
283 Water
284 Dark
285 Dark
286 Normal
287 Normal
288 Bug
289 Bug
290 Bug
291 Bug
292 Bug
293 Water
294 Water
295 Water
296 Grass
297 Grass
298 Grass
299 Normal
300 Normal
301 Water
302 Water
303 Psychic
304 Psychic
305 Psychic
306 Psychic
307 Bug
308 Bug
309 Grass
310 Grass
311 Normal
312 Normal
313 Normal
314 Bug
315 Bug
316 Bug
317 Normal
318 Normal
319 Normal
320 Fighting
321 Fighting
322 Normal
323 Rock
324 Normal
325 Normal
326 Dark
327 Dark
328 Steel
329 Steel
330 Steel
331 Steel
332 Steel
333 Steel
334 Fighting
335 Fighting
336 Fighting
337 Electric
338 Electric
339 Electric
340 Electric
341 Electric
342 Bug
343 Bug
344 Grass
345 Poison
346 Poison
347 Water
348 Water
349 Water
350 Water
351 Water
352 Fire
353 Fire
354 Fire
355 Fire
356 Psychic
357 Psychic
358 Normal
359 Ground
360 Ground
361 Ground
362 Grass
363 Grass
364 Normal
365 Dragon
366 Dragon
367 Normal
368 Poison
369 Rock
370 Rock
371 Water
372 Water
373 Water
374 Water
375 Ground
376 Ground
377 Rock
378 Rock
379 Rock
380 Rock
381 Water
382 Water
383 Normal
384 Normal
385 Ghost
386 Ghost
387 Ghost
388 Ghost
389 Ghost
390 Grass
391 Psychic
392 Dark
393 Dark
394 Psychic
395 Ice
396 Ice
397 Ice
398 Ice
399 Ice
400 Ice
401 Water
402 Water
403 Water
404 Water
405 Water
406 Dragon
407 Dragon
408 Dragon
409 Dragon
410 Steel
411 Steel
412 Steel
413 Steel
414 Rock
415 Ice
416 Steel
417 Dragon
418 Dragon
419 Dragon
420 Dragon
421 Water
422 Water
423 Ground
424 Ground
425 Dragon
426 Dragon
427 Steel
428 Psychic
429 Psychic
430 Psychic
431 Psychic
432 Grass
433 Grass
434 Grass
435 Fire
436 Fire
437 Fire
438 Water
439 Water
440 Water
441 Normal
442 Normal
443 Normal
444 Normal
445 Normal
446 Bug
447 Bug
448 Electric
449 Electric
450 Electric
451 Grass
452 Grass
453 Rock
454 Rock
455 Rock
456 Rock
457 Bug
458 Bug
459 Bug
460 Bug
461 Bug
462 Bug
463 Bug
464 Electric
465 Water
466 Water
467 Grass
468 Grass
469 Water
470 Water
471 Normal
472 Ghost
473 Ghost
474 Normal
475 Normal
476 Normal
477 Ghost
478 Dark
479 Normal
480 Normal
481 Psychic
482 Poison
483 Poison
484 Steel
485 Steel
486 Rock
487 Psychic
488 Normal
489 Normal
490 Ghost
491 Dragon
492 Dragon
493 Dragon
494 Dragon
495 Normal
496 Fighting
497 Fighting
498 Fighting
499 Ground
500 Ground
501 Poison
502 Poison
503 Poison
504 Poison
505 Grass
506 Water
507 Water
508 Water
509 Grass
510 Grass
511 Grass
512 Dark
513 Electric
514 Normal
515 Ground
516 Grass
517 Electric
518 Fire
519 Fairy
520 Bug
521 Grass
522 Ice
523 Ground
524 Ice
525 Normal
526 Psychic
527 Psychic
528 Rock
529 Ghost
530 Ice
531 Electric
532 Electric
533 Electric
534 Electric
535 Electric
536 Electric
537 Psychic
538 Psychic
539 Psychic
540 Steel
541 Water
542 Fire
543 Normal
544 Ghost
545 Ghost
546 Psychic
547 Water
548 Water
549 Dark
550 Grass
551 Grass
552 Normal
553 Psychic
554 Grass
555 Grass
556 Grass
557 Fire
558 Fire
559 Fire
560 Water
561 Water
562 Water
563 Normal
564 Normal
565 Normal
566 Normal
567 Normal
568 Dark
569 Dark
570 Grass
571 Grass
572 Fire
573 Fire
574 Water
575 Water
576 Psychic
577 Psychic
578 Normal
579 Normal
580 Normal
581 Electric
582 Electric
583 Rock
584 Rock
585 Rock
586 Psychic
587 Psychic
588 Ground
589 Ground
590 Normal
591 Normal
592 Fighting
593 Fighting
594 Fighting
595 Water
596 Water
597 Water
598 Fighting
599 Fighting
600 Bug
601 Bug
602 Bug
603 Bug
604 Bug
605 Bug
606 Grass
607 Grass
608 Grass
609 Grass
610 Water
611 Ground
612 Ground
613 Ground
614 Fire
615 Fire
616 Fire
617 Grass
618 Bug
619 Bug
620 Dark
621 Dark
622 Psychic
623 Ghost
624 Ghost
625 Water
626 Water
627 Rock
628 Rock
629 Poison
630 Poison
631 Dark
632 Dark
633 Normal
634 Normal
635 Psychic
636 Psychic
637 Psychic
638 Psychic
639 Psychic
640 Psychic
641 Water
642 Water
643 Ice
644 Ice
645 Ice
646 Normal
647 Normal
648 Electric
649 Bug
650 Bug
651 Grass
652 Grass
653 Water
654 Water
655 Water
656 Bug
657 Bug
658 Grass
659 Grass
660 Steel
661 Steel
662 Steel
663 Electric
664 Electric
665 Electric
666 Psychic
667 Psychic
668 Ghost
669 Ghost
670 Ghost
671 Dragon
672 Dragon
673 Dragon
674 Ice
675 Ice
676 Ice
677 Bug
678 Bug
679 Ground
680 Fighting
681 Fighting
682 Dragon
683 Ground
684 Ground
685 Dark
686 Dark
687 Normal
688 Normal
689 Normal
690 Dark
691 Dark
692 Fire
693 Bug
694 Dark
695 Dark
696 Dark
697 Bug
698 Bug
699 Steel
700 Rock
701 Grass
702 Flying
703 Flying
704 Electric
705 Electric
706 Dragon
707 Dragon
708 Ground
709 Ground
710 Dragon
711 Dragon
712 Dragon
713 Water
714 Water
715 Normal
716 Normal
717 Bug
718 Grass
719 Grass
720 Grass
721 Fire
722 Fire
723 Fire
724 Water
725 Water
726 Water
727 Normal
728 Normal
729 Normal
730 Fire
731 Fire
732 Bug
733 Bug
734 Bug
735 Fire
736 Fire
737 Fairy
738 Fairy
739 Fairy
740 Grass
741 Grass
742 Fighting
743 Fighting
744 Normal
745 Psychic
746 Psychic
747 Psychic
748 Steel
749 Steel
750 Steel
751 Steel
752 Fairy
753 Fairy
754 Fairy
755 Fairy
756 Dark
757 Dark
758 Rock
759 Rock
760 Poison
761 Poison
762 Water
763 Water
764 Electric
765 Electric
766 Rock
767 Rock
768 Rock
769 Rock
770 Fairy
771 Fighting
772 Electric
773 Rock
774 Dragon
775 Dragon
776 Dragon
777 Steel
778 Ghost
779 Ghost
780 Ghost
781 Ghost
782 Ghost
783 Ghost
784 Ghost
785 Ghost
786 Ghost
787 Ghost
788 Ice
789 Ice
790 Flying
791 Flying
792 Fairy
793 Dark
794 Dragon
795 Rock
796 Rock
797 Psychic
798 Psychic
799 Fire

In [19]:
#Accessing rows based on a particular column
df.loc[df['Type 1'] == 'Grass']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,56,61,65,48,45,38,6,False
719,651,Quilladin,Grass,NaN,61,78,95,56,58,57,6,False
720,652,Chesnaught,Grass,Fighting,88,107,122,74,75,64,6,False
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False

In [26]:
#sorting data
df.sort_values('Name', ascending=False)
df.sort_values(['Type 1', 'HP'], ascending=[1,0]) # sorted with Type 1 ascending and HP descending

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
520,469,Yanmega,Bug,Flying,86,76,86,116,56,95,4,False
698,637,Volcarona,Bug,Fire,85,60,65,135,105,100,5,False
231,214,Heracross,Bug,Fighting,80,125,75,40,95,85,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
678,617,Accelgor,Bug,NaN,80,70,40,100,60,145,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
106,98,Krabby,Water,NaN,30,105,90,25,25,50,1,False
125,116,Horsea,Water,NaN,30,40,70,70,25,60,1,False
129,120,Staryu,Water,NaN,30,45,55,70,55,85,1,False
139,129,Magikarp,Water,NaN,20,10,55,15,20,80,1,False
381,349,Feebas,Water,NaN,20,15,20,10,55,80,3,False

In [27]:
#adding a new column
df['Total'] = df['HP'] + df['Attack'] + df['Defense'] + df['Sp. Atk'] + df['Sp. Def'] + df['Speed']

In [28]:
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

In [29]:
#dropping columns
df = df.drop(columns=['Total'])

In [30]:
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [33]:
# Faster way to add a new column
df['Total'] = df.iloc[:,4:10].sum(axis=1) # axis = 1 adds horizontally axis = 0 adds vertically
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

In [34]:
#cols = list(df.columns)  gets all the columns in a list
#df.to_csv('name you give the file')  modifying / creating a file
#filtering Data
df.loc[df['Type 1'] == 'Grass']

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
48,43,Oddish,Grass,Poison,45,50,55,75,65,30,1,False,320
...,...,...,...,...,...,...,...,...,...,...,...,...,...
718,650,Chespin,Grass,NaN,56,61,65,48,45,38,6,False,313
719,651,Quilladin,Grass,NaN,61,78,95,56,58,57,6,False,405
720,652,Chesnaught,Grass,Fighting,88,107,122,74,75,64,6,False,530
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False,350
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False,531

In [67]:
#filtering with one or more conditions
df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison') & (df['HP'] >70)] # and in pands is & or in |

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False,490
77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,False,490
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False,464

In [68]:
new_df =df.loc[(df['Type 1'] == 'Grass') & (df['Type 2'] == 'Poison') & (df['HP'] >70)]

In [69]:
new_df.reset_index()

,index,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
1,3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
2,50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False,490
3,77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,False,490
4,652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False,464

In [70]:
new_df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
50,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False,490
77,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,False,490
652,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False,464

In [71]:
new_df.reset_index(drop=True, inplace=True) #drop old index

In [72]:
new_df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
1,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
2,45,Vileplume,Grass,Poison,75,80,85,110,90,50,1,False,490
3,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,False,490
4,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False,464

In [74]:
#filtering with a specific sub-string contained in a string
df.loc[df['Name'].str.contains('Mega')]
# the opposite
df.loc[~df['Name'].str.contains('Mega')]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False,405
...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True,600
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [75]:
import re  #regular expressions
df.loc[df['Type 1'].str.contains('fire| glass', flags=re.I, regex=True)]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False,405
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False,534
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False,634
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False,634
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,1,False,299
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,1,False,505
63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,1,False,350
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False,555
83,77,Ponyta,Fire,NaN,50,85,55,65,65,90,1,False,410
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False,500
135,126,Magmar,Fire,NaN,65,95,57,100,85,93,1,False,495
147,136,Flareon,Fire,NaN,65,130,60,95,110,65,1,False,525
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True,580
169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,2,False,309
170,156,Quilava,Fire,NaN,58,64,58,80,65,80,2,False,405
171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,2,False,534
236,218,Slugma,Fire,NaN,40,40,40,70,40,20,2,False,250
237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,False,410
259,240,Magby,Fire,NaN,45,75,37,70,55,83,2,False,365
263,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True,580
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True,680
276,255,Torchic,Fire,NaN,45,60,40,70,50,45,3,False,310
277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,3,False,405
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,3,False,530
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False,630
352,322,Numel,Fire,Ground,60,60,40,65,45,35,3,False,305
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,3,False,460
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False,560
355,324,Torkoal,Fire,NaN,70,85,140,85,70,20,3,False,470
435,390,Chimchar,Fire,NaN,44,58,44,58,44,61,4,False,309
436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,4,False,405
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,4,False,534
518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,4,False,540
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,4,True,600
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,5,False,308
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False,418
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,5,False,528
572,513,Pansear,Fire,NaN,50,53,48,53,48,64,5,False,316
573,514,Simisear,Fire,NaN,75,98,63,98,63,101,5,False,498
614,554,Darumaka,Fire,NaN,70,90,45,15,45,50,5,False,315
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,5,False,480
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,5,False,540
692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,5,False,484
721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,6,False,307
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,6,False,409
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,6,False,534
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,6,False,382
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,6,False,499
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False,369
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False,507
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [9]:
count = 0
p = [[1,1,1,0,1,1],[0,0,1,1,1,1]]
for i in range(len(p[0])):
    if p[0][i] == p[1][i]:
        count+=1
print(count)

3

In [2]:
matrix = [[2,3,4,5,6],[3,4,6,7,8],[3,5,8,9,8]]
print(matrix[-1][-1])

8

In [1]:
#if we had an excel file we would read it with
# df = pd.read_excel("name of excel file")

#for a dictionary containing lists, same applies to a list containing dictionaries
# df = pd.DataFrame(dictionary)

#a list that contains tuples
#eg weather_data = [('1/1/2017', 22,6, 'Snow'), 
 #                  ('1/2/2017', 35,8, 'sunny')]
# df = pd.DataFrame(weather_data, columns=['day', 'temperature', 'windspeed', 'event' ])   

# if you have a file you can specify the row you want to be the header by pasing the argument header=(row_number) or skiprow
#if you dont want an header header=None
#if you want to read a particular no of rows pass as an argument nrows=no of rows

In [ ]:
# during cleaning you can pass na_values=["the non number values"] as an argument in pd.read_csv()
# writing a new csv
#df.to_csv('new.csv', index=False)